Main.exe:SliderIconType.o SpinnerIconType.o HopperIconType.o Main.o
	g++ -std=c++11 SliderIconType.o SpinnerIconType.o HopperIconType.o Main.o -o Main.exe
	rm *.o
Main.o:
	g++ -std=c++11 -c -g Main.cpp -o Main.o
SliderIconType.o:
	g++ -std=c++11 -c -g SliderIconType.cpp -o SliderIconType.o
SpinnerIconType.o:
	g++ -std=c++11 -c -g SpinnerIconType.cpp -o SpinnerIconType.o
HopperIconType.o:
	g++ -std=c++11 -c -g HopperIconType.cpp -o HopperIconType.o
